[package]
name = "whatever"
version = "0.0.1"
authors = ["petechen <15736755067@163.com>"]
edition = "2018"
homepage = "https://github.com/ptechen"
documentation = "https://github.com/ptechen/whatever/blob/main/README.md"
repository = "https://github.com/ptechen/whatever.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "error"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clickhouse = "^0.8.1"
csv = "^1.1.6"
enum-repr = "^0.2.6"
libc = "^0.2.104"
rbatis = "^2.1.4"
reqwest = "^0.11.6"
serde = "^1.0.130"
serde_derive = "^1.0.130"
serde_json = "^1.0.68"
zip = "^0.5.13"
