[package]
name = "whatever"
version = "0.0.4"
authors = ["petechen <15736755067@163.com>"]
edition = "2018"
homepage = "https://github.com/ptechen"
documentation = "https://github.com/ptechen/whatever/blob/main/README.md"
repository = "https://github.com/ptechen/whatever.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Contains all error types."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^3.3.2"
chrono = "^0.4.19"
clickhouse = "^0.8.1"
csv = "^1.1.6"
enum-repr = "^0.2.6"
libc = "^0.2.104"
rbatis = "^2.1.4"
reqwest = "^0.11.6"
serde = "^1.0.130"
serde_derive = "^1.0.130"
serde_json = "^1.0.68"
sqlx = { version = "0.5", features = ["mysql", "time", "decimal", "json", "chrono", "macros","runtime-async-std-native-tls"] }
zip = "^0.5.13"

[features]
full = ["std_err", "sqlx_err", "rbatis_err", "actix_err", "reqwest_err", "serde_json_err", "chrono_err", "zip_err", "clickhouse_err", "csv_err"]
std_err = []
sqlx_err = []
rbatis_err = []
actix_err = []
reqwest_err = []
serde_json_err = []
chrono_err = []
zip_err = []
clickhouse_err = []
csv_err = []
